export const NIFTY_50 = [
  'RELIANCE', 'TCS', 'HDFCBANK', 'BHARTIARTL', 'ICICIBANK',
  'INFY', 'SBIN', 'HINDUNILVR', 'ITC', 'LT',
  'KOTAKBANK', 'AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'M&M',
  'MARUTI', 'TITAN', 'SUNPHARMA', 'NESTLEIND', 'POWERGRID',
  'NTPC', 'ULTRACEMCO', 'ADANIENT', 'WIPRO', 'TATAMOTORS',
  'JSWSTEEL', 'TATASTEEL', 'ASIANPAINT', 'HCLTECH', 'TECHM',
  'COALINDIA', 'ONGC', 'GRASIM', 'INDUSINDBK', 'CIPLA',
  'DRREDDY', 'EICHERMOT', 'BAJAJ-AUTO', 'HEROMOTOCO', 'TATACONSUM',
  'BRITANNIA', 'DIVISLAB', 'APOLLOHOSP', 'HINDALCO', 'BPCL',
  'SBILIFE', 'HDFCLIFE', 'ADANIPORTS', 'LTIM', 'SHRIRAMFIN',
];
